### PR TITLE
Changed logger

### PR DESCRIPTION
**Pull request by TBotV63**
I changed some stuff in the main class to resemble the preferred way of retrieveing a logger.

### CODE REVIEW

**Comment by hitech95** [comment]
I would like to have a single point to manage the log. Because if the plugin is not in debug mode shouldn't write "shit" in chat.

What I wonder is whether correct to do it this way :D

**Comment by TBotV63** [comment]
No, for that you have logging levels. If your stuff is debug only, then just set the level to debug.

**Comment by hitech95** [comment]
How do I specify which mode the plugin is?

**Comment by TBotV63** [comment]
You don't. The server decides wether it's in debug mode or not.
But if you really want to change that manually, then you should get the root logger and change its threshold.

**Comment by hitech95** [comment]
Can you give me some example?

**Comment by hitech95** [comment]
I close, found an alternative solution.

**Pull request closed without merging**
